# Copyright 2016 Peter Dimov
# Copyright 2019 Moskvin Aleksey <zerg1996@yandex.ru>
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - 22-implement-AppVeyorCI

platform:
  - x64

os: unstable

cache:
  - C:\Boost -> appveyor.yml

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARGS: --toolset=msvc-14.2 address-model=64 cxxstd=17
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
      TARGETS_CMAKE: multiprecision_test_suite_arithmetic_tests multiprecision_test_suite_cpp_int_tests multiprecision_test_suite_functions_and_limits

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARGS: --toolset=msvc-14.2 address-model=64 cxxstd=17
      TARGETS_CMAKE: multiprecision_test_suite_functions_and_limits

install:
  - SET boost_install=false
  - cd ..
  - git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init libs/config
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\multiprecision
  - git submodule update --init tools/boostdep
  - python tools/boostdep/depinst/depinst.py multiprecision
  - bootstrap.bat
  - b2 headers
  - b2 install

build: off

test_script:
  - cmd: cd libs\multiprecision
  - cmd: mkdir cmake-build
  - cmd: cd cmake-build
  - cmd: cmake -DBoost_DIR=C:/Boost/lib/cmake/boost-1.72.0 -DBUILD_TESTS=TRUE -DCMAKE_CXX_STANDARD=14 -DBUILD_WITH_CI_KNOWN_ISSUES_SUPPRESS=TRUE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE --build ..
  - cmd: cmake --build C:/projects/boost-root/libs/multiprecision/cmake-build --target %TARGETS_CMAKE%
