# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - 22-implement-AppVeyorCI

platform:
  - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARGS: --toolset=msvc-14.2 address-model=64 cxxstd=17
      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits

install:
  - cd ..
  - git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init libs/config
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\multiprecision
  - git submodule update --init tools/boostdep
  - python tools/boostdep/depinst/depinst.py multiprecision
  - bootstrap
  - b2 headers
  - b2 install

test_script:
  - cd $TRAVIS_BUILD_DIR && mkdir cmake-build && cd cmake-build;
