# Copyright 2016 Peter Dimov
# Copyright 2019 Moskvin Aleksey <zerg1996@yandex.ru>
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - 22-implement-AppVeyorCI

platform:
  - x64

os: unstable

#environment:
#  matrix:
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      ARGS: --toolset=msvc-14.2 address-model=64 cxxstd=17
#      TARGETS: arithmetic_tests cpp_int_tests functions_and_limits
#      APPVEYOR_RDP_PASSWORD: Rdppassword0!

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: cmake --version

environment:
  GENERATOR: "Visual Studio 14 2015 Win64"
  CONFIG: Debug
  PATH: "%BOOST_LIBRARYDIR%;%PATH%"
  matrix:
    - BOOST_ROOT: "C:\\Libraries\\boost_1_60_0"
      BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_60_0\\lib64-msvc-14.0"
    - BOOST_ROOT: "C:\\Libraries\\boost_1_62_0"
      BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_62_0\\lib64-msvc-14.0"

install:
  - cd ..
  - git clone -b boost-1.71.0 --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init libs/config
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\multiprecision
  - git submodule update --init tools/boostdep
  - python tools/boostdep/depinst/depinst.py multiprecision
  - bootstrap.bat
  - b2 headers
  - b2 --prefix=C:/local install

build: off

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: mkdir cmake-build
  - cmd: cd cmake-build
  - cmd: cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE="%CONFIG%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
  - cmd: cmake -DBOOST_ROOT=C:\Boost -DBUILD_TESTS=TRUE -DCMAKE_CXX_STANDARD=14 -DBUILD_WITH_CI_KNOWN_ISSUES_SUPPRESS=TRUE --build %APPVEYOR_BUILD_FOLDER%

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
